### ISSUE TITLE
Add multiple-of()

### ISSUE THREAD

**Issue by danielguillan** [danielguillan/quantity-queries#16]
Continuation of #13

**Comment by robsonsobral** [comment]
Would you accept a PR, @danielguillan ?

**Comment by danielguillan** [comment]
Absolutely! Can you please share what the API would look like and some example input/output code before doing the PR?

**Comment by robsonsobral** [comment]
Let get back to this? I'm sorry it took so long. I ended using my own implementation, but I think it can be helpful to others, specially as the use of grid layout increases.

---

I'm sorry! I messed up everything! I'm talking about multiples, no factors! The intention is to target quantities which are divisible by a number, so multiples! I'm so sorry!

---

I guess my [old sample](https://codepen.io/robsonsobral/pen/rNzeLJj) still works.

The API could be something like:

```scss
.foobar {
  @include multiple-of(3) {
    background-color: cyan;
  }
  
  @include multiple-of(5) {
    background-color: magenta;
    
    &:nth-child(2n) { // a nesting sample for every even element among a multiple of 5 quantity
      background: green;
    }
  }
}
```

And the output:

```css
.foobar:nth-last-child(3n):first-child,
.foobar:nth-last-child(3n):first-child ~ * {
  background-color: cyan;
}
.foobar:nth-last-child(5n):first-child,
.foobar:nth-last-child(5n):first-child ~ * {
  background-color: magenta;
}
.foobar:nth-last-child(5n):first-child:nth-child(2n),
.foobar:nth-last-child(5n):first-child ~ *:nth-child(2n) {
  background: green;
}
```
