### ISSUE TITLE
Add first-row last-row mixins

### ISSUE THREAD

**Issue by Nirazul** [danielguillan/quantity-queries#9]
Thanks for the nice compilation of mixins!
I think it would be a cool addition to also implement first-row and last-row mixins displayed in [this article](http://keithclark.co.uk/articles/targeting-first-and-last-rows-in-css-grid-layouts/).

I occasionally use this mixin for targeting last rows:
```
/// Targets the last row in a grid of constant column count
/// @link http://keithclark.co.uk/articles/targeting-first-and-last-rows-in-css-grid-layouts/
/// @param {number} $num-cols - The number of columns within the context
///
@mixin last-row($num-cols) {
  $selector: nth(nth(&, 1), length(nth(&, 1)));

  &:nth-child(#{$num-cols}n + 1):nth-last-child(-n + #{$num-cols}),
  &:nth-child(#{$num-cols}n + 1):nth-last-child(-n + #{$num-cols}) ~ #{$selector} {
    @content;
  }
}

/// Usage
///
ul > li {
  @include last-row(2) {
    justify-content: center;
  }
}
```

**Comment by danielguillan** [comment]
Very interesting. I'll take a look at it. Thanks for the suggestion @Nirazul!

**Comment by robsonsobral** [comment]
@danielguillan , would you accept a PR?

**Comment by robsonsobral** [comment]
@danielguillan ?

**Comment by robsonsobral** [comment]
I did some tests.

Based [on this article](https://keithclark.co.uk/articles/targeting-first-and-last-rows-in-css-grid-layouts/), we could have something like:

```scss
ul > li {
    @include first(4) { color: red; }
}

ul > li {
    @include last(6) { color: blue; }
}

ul > li {
    @include last-or-remainder(6) { color: blue; }
}
```

```css
ul > li:nth-child(-n+4) {
  color: red;
}

ul > li:nth-child(6n+1):nth-last-child(-n+6) {
  color: blue;
}

ul > li:nth-child(6n+1):nth-last-child(-n+6),
ul > li:nth-child(6n+1):nth-last-child(-n+6) ~ li {
  color: blue;
}
```

However, in these cases the total quantity doesn't matter, so... I'm not sure these mixins have a place in here. I think they do, but I'm not the boss.
